library(tidyverse)
library(car)
library(knitr)

setwd("C:/Users/Anton/Desktop/MPSOF-1/Emperic")
d <- read.csv(file = 'performance.csv',sep = ",")
mean(d$timeOriginal)
mean(d$timeOptimized)
sd(d$timeOriginal)
sd(d$timeOptimized)
var(d$timeOriginal)
var(d$timeOptimized)
median(d$timeOriginal)
median(d$timeOptimized)
